Frontend/MvcApp/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApp.Models;
using MvcApp.DataModel;
using MvcApp.Services;
using Newtonsoft.Json;


namespace MvcApp.Controllers;

public class AdminController : Controller
{
    private readonly ApplicationDBContext _db;
    private readonly AdminService service;
    private readonly IConfigurationRoot configurationBuilder;

    public AdminController(ApplicationDBContext db)
    {
        _db = db;
        service = new AdminService(db);
        configurationBuilder = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
    }
    [HttpGet]
    public vwModelsandAdmins Index()
    {
        var modelsandAdmins = new vwModelsandAdmins();
        modelsandAdmins.adminCreds = service.GetAdmins();
        modelsandAdmins.LoginUserDetails = service.GetCurrentUser();
        modelsandAdmins.SavedModels = service.getSavedModels();
        return modelsandAdmins;
    }

    [HttpPost("AddAdmin")]

    public ActionResult AddAdmin(AdminCreds admin)
    {
        try
        {
            var result = service.AddAdmin(admin);
            return View("~/Views/Admin/Index.cshtml", Index());
        }
        catch
        {
            return View("~/Views/Admin/Index.cshtml", Index());
        }
    }

    [HttpGet("VerifyUser")]
    public ActionResult VerifyUser(AdminCreds creds)
    {
        try
        {
            var result = service.ValidateAdmin(creds);
            if (result == null)
            {
                var values = new ContentResult() { Content = "Unauthorized", StatusCode = StatusCodes.Status401Unauthorized, ContentType = "application/json" };
                return View("~/Views/Home/LoginScreen.cshtml", new { Values = values });
            }
            else
            {
                var list_values = Index();
                // var values = new ContentResult() { Content = result.name, StatusCode = StatusCodes.Status200OK };
                return View("~/Views/Admin/Index.cshtml", list_values);
            }
        }
        catch (Exception e)
        {
            var values = new ContentResult() { Content = null, StatusCode = StatusCodes.Status400BadRequest };
            return View("~/Views/Home/LoginScreen.cshtml", new { Values = values });
        }
    }

    [HttpPost("UploadModel")]
    public ActionResult<vwModelsandAdmins> UploadModel(IFormFile file)
    {
        try
        {

            UploadModel model = new UploadModel();
            model.file = file;
            var cloud_data = new CloudCredsModel();
            cloud_data.project_id = configurationBuilder.GetValue<string>("CloudDetails:project_id");
            cloud_data.location = configurationBuilder.GetValue<string>("CloudDetails:location");
            // cloud_data.bucket_name = configurationBuilder.GetValue<String>("CloudDetails:bucket_name");
            // model.data = '{"project_id":"cloudcomputing-411615", "location":"us-central1"}';
            model.data = JsonConvert.SerializeObject(cloud_data);
            var result = service.UploadModel(model);
            ViewBag.Message = "Upload Successful";
            var vwModel = new vwModelsandAdmins();
            vwModel = Index();
            return View("~/Views/Admin/Index.cshtml", vwModel);
        }
        catch (Exception e)
        {
            ViewBag.Message = e;
            var vwModel = new vwModelsandAdmins();
            vwModel = Index();
            return View("~/Views/Admin/Index.cshtml", vwModel);
        }
    }

}

Frontend/MvcApp/Controllers/GuestController.cs
using Microsoft.AspNetCore.Mvc;
namespace MvcApp.Controllers;

using MvcApp.DataModel;
using MvcApp.Models;
using MvcApp.Services;


public class GuestController : Controller
{
    private readonly IConfigurationRoot configurationBuilder;
    private readonly ApplicationDBContext _db;
    private readonly GuestService service;
    public GuestController(ApplicationDBContext db)
    {
        _db = db;
        service = new GuestService(db);
        configurationBuilder = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
    }
    [HttpGet]
    public IActionResult Index()
    {
        List<vwSavedModel> models = service.getSavedModels();
        return View(models);
    }

    public ActionResult SetCurrentBucketName(string bucket_name)
    {
        service.set_current_model_bucket(bucket_name);
        return View("~/Views/Guest/model_page.cshtml");
    }
    [HttpPost("Predict_Output")]
    public async Task<ActionResult> Predict_Output(IFormFile file)
    {
        try
        {
            var modelData = new PredictModelData();
            if (file.Length > 0)
            {
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    modelData.input_file = ms.ToArray();
                }
            }
            var imageExtension = Path.GetExtension(file.FileName)?.ToLowerInvariant();
            modelData.bucket_name = service.GetCurrentModelBucketName();
            modelData.project_id = configurationBuilder.GetValue<String>("CloudDetails:project_id");
            var input_url = configurationBuilder.GetValue<String>("CloudURLs:input_url");
            var predict_url = configurationBuilder.GetValue<String>("CloudURLs:predict_url");
            var final_prediction = await service.SendInputToCloud(modelData, input_url, predict_url, imageExtension.Substring(1, imageExtension.Length - 1));
            ViewBag.Message = final_prediction.ToString();
            // var result = service.AddAdmin(admin);
            return View("~/Views/Guest/model_page.cshtml");
        }
        catch
        {
            ViewBag.Message = "Error while processing request";
            return View("~/Views/Guest/model_page.cshtml");
        }
    }

}

Frontend/MvcApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcApp.Models;
using Microsoft.AspNetCore.Http;
using System.Web;

namespace MvcApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
    public ActionResult NavigateToLoginScreen()
    {
        var values = new ContentResult() { Content = null, StatusCode = StatusCodes.Status100Continue };

        return View("~/Views/Home/LoginScreen.cshtml", new { Values = values });
    }


}

Frontend/MvcApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html>

<head>
    <title>@ViewData["Title"]</title>
    <style>
        /* Button container */
        .button-container {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-wrap: wrap;
            /* Allow buttons to wrap */
            margin-top: 15vh;
            /* Add space above button container */
        }
    </style>
</head>

<body>
    <div>
        <header>
            <h1>Welcome to MLDeployX</h1>
        </header>

        <div class="button-container">
            <a href='@Url.Action("NavigateToLoginScreen", "Home")'>
                <button class="button">Admin Screen</button>
            </a>
            <a href='@Url.Action("Index", "Guest")'>
                <button class="button">Guest Screen</button>
            </a>
        </div>
    </div>


</body>

</html>

Frontend/MvcApp/Views/Home/LoginScreen.cshtml
@{
    ViewData["Title"] = "Login Page";
}

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f8f9fa;
    }

    .login-container {
        background-color: #fff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        max-width: 400px;
        width: 100%;
    }

    .error-message {
        color: #dc3545;
        font-size: smaller;
        margin-top: 10px;
    }

    .close {
        font-size: smaller;
    }

    .container {
        max-width: 500px;
        max-height: 50vh;
    }

    .form-div {
        margin-top: 5vh;
    }
</style>

<body>
    <header>
        <h1 class="text-center">Admin Login</h1>
    </header>

    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong><span class="error-message"></span></strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="form-div">
        @using (Html.BeginForm("VerifyUser", "Admin", FormMethod.Get, new
        {
            enctype = "multipart/form-data",
            onsubmit = "return validateForm(event)",


        }))
        {
            <div class="form-group">
                <label for="UserName">User Name</label>
                <input type="text" class="form-control" id="UserName" name="username" aria-describedby="emailHelp"
                    placeholder="Enter username">
            </div>
            <div class="form-group">
                <label for="Password">Password</label>
                <input type="password" class="form-control" id="Password" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary btn-block">Submit</button>
            <a href="@Url.Action("Index", "Home")">
                <button type="button" class="btn btn-light btn-block">Back</button>
            </a>

        }
    </div>



    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.alert').hide();
            $('.close').on("click", function () {
                $('.alert').hide();
            });
            if (@Html.Raw(Json.Serialize(Model.Values.StatusCode)) == 401) {
                $('.error-message').empty();
                $('.error-message').html("Invalid Credentials");
                $('.alert').show();
            }
            else if (@Html.Raw(Json.Serialize(Model.Values.StatusCode)) == 400) {
                $('.error-message').empty();
                $('.error-message').html("Bad gateway. Please try again");
                $('.alert').show();
            }
        });

        function validateForm(event) {
            var username = $('#UserName').val();
            var password = $('#Password').val();
            $('.error-message').empty();

            var errorMessage = "";

            if (!username || username.trim() === "") {
                errorMessage += "Please enter a valid username.<br>";
            }
            if (!password || password.trim() === "") {
                errorMessage += "Please enter a valid password.";
            }

            if (errorMessage !== "") {
                $('.error-message').html(errorMessage);
                $('.alert').show();
                return false;
            }
            return true;
        }
    </script>
</body>